name: 'Github Pages Deployment'

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yml'
  schedule:
    - cron: '20 4 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: 'git / checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 'ruby / setup'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: 'ruby / install'
        run: cd ../.stranger-quarkdown && bundle install && cd ../scripts && bundle install

      - name: 'node / setup'
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: 'node / install'
        run: npm install

      - name: 'svelte / build'
        run: |
          npm run build

      - name: 'github / upload artifacts'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'github / deploy'
        id: deployment
        uses: actions/deploy-pages@v4
